
// Generated by Cadence Genus(TM) Synthesis Solution 21.14-s082_1
// Generated on: Apr  8 2026 16:35:30 IST (Apr  8 2026 11:05:30 UTC)

// Verification Directory fv/pic_top 

module controller_fsm(irq_req, irq_to_cpu, clk, reset, valid, irq_id,
     cpu_ack);
  input clk, reset, valid, cpu_ack;
  input [2:0] irq_id;
  output irq_req;
  output [2:0] irq_to_cpu;
  wire clk, reset, valid, cpu_ack;
  wire [2:0] irq_id;
  wire irq_req;
  wire [2:0] irq_to_cpu;
  wire [1:0] state;
  wire n_0, n_1, n_2, n_3, n_4, n_5;
  DFFRHQX1 irq_req_reg(.RN (n_0), .CK (clk), .D (n_5), .Q (irq_req));
  SDFFRHQX1 \irq_to_cpu_reg[2] (.RN (n_0), .CK (clk), .D (irq_id[2]),
       .SI (irq_to_cpu[2]), .SE (n_2), .Q (irq_to_cpu[2]));
  AO21X1 g255__2398(.A0 (state[0]), .A1 (irq_req), .B0 (n_4), .Y (n_5));
  SDFFRHQX1 \irq_to_cpu_reg[1] (.RN (n_0), .CK (clk), .D (irq_id[1]),
       .SI (irq_to_cpu[1]), .SE (n_2), .Q (irq_to_cpu[1]));
  SDFFRHQX1 \irq_to_cpu_reg[0] (.RN (n_0), .CK (clk), .D (irq_id[0]),
       .SI (irq_to_cpu[0]), .SE (n_2), .Q (irq_to_cpu[0]));
  DFFRHQX1 \state_reg[0] (.RN (n_0), .CK (clk), .D (n_3), .Q
       (state[0]));
  OAI31X1 g259__5107(.A0 (state[0]), .A1 (n_1), .A2 (cpu_ack), .B0
       (n_2), .Y (n_4));
  NOR3BX1 g260__6260(.AN (valid), .B (state[0]), .C (state[1]), .Y
       (n_3));
  NAND2XL g261__4319(.A (state[0]), .B (n_1), .Y (n_2));
  INVXL g263(.A (reset), .Y (n_0));
  DFFRX1 \state_reg[1] (.RN (n_0), .CK (clk), .D (n_4), .Q (state[1]),
       .QN (n_1));
endmodule

module pic_top(clk, reset, irq, mask, cpu_ack, irq_req, irq_to_cpu);
  input clk, reset, cpu_ack;
  input [7:0] irq, mask;
  output irq_req;
  output [2:0] irq_to_cpu;
  wire clk, reset, cpu_ack;
  wire [7:0] irq, mask;
  wire irq_req;
  wire [2:0] irq_to_cpu;
  wire [2:0] irq_id;
  wire [2:0] u4_priority_ptr;
  wire n_0, n_1, n_2, n_3, n_4, n_5, n_6, n_7;
  wire n_8, n_9, n_10, n_11, n_12, n_13, n_14, n_15;
  wire n_16, n_17, n_18, n_19, n_20, n_21, n_22, n_23;
  wire n_24, n_25, n_26, n_27, n_28, n_29, n_30, n_31;
  wire n_32, n_33, n_34, n_35, n_36, n_37, n_38, n_39;
  wire n_40, n_41, n_42, n_43, n_44, n_45, n_46, n_47;
  wire n_48, n_49, n_50, n_51, n_52, n_54, n_55, n_56;
  wire n_57, n_59, n_60, n_61, n_62, n_63, n_64, n_65;
  wire n_66, n_67, n_69, n_70, n_71, n_72, n_96, valid;
  controller_fsm u3(.irq_req (irq_req), .irq_to_cpu (irq_to_cpu), .clk
       (clk), .reset (reset), .valid (valid), .irq_id (irq_id),
       .cpu_ack (cpu_ack));
  NAND2XL g1875__8428(.A (n_96), .B (n_70), .Y (irq_id[1]));
  OR2X1 g1876__5526(.A (n_69), .B (n_72), .Y (irq_id[0]));
  AOI21X1 g1877__6783(.A0 (n_61), .A1 (n_2), .B0 (n_72), .Y (n_70));
  NAND2XL g1878__3680(.A (n_56), .B (n_71), .Y (n_72));
  NAND3XL g1879__1617(.A (n_14), .B (n_67), .C (n_2), .Y (valid));
  OAI31X1 g1880__2802(.A0 (n_61), .A1 (n_65), .A2 (irq_id[2]), .B0
       (n_64), .Y (n_69));
  NAND2XL g1881__1705(.A (n_62), .B (n_2), .Y (n_71));
  INVX1 g1882(.A (irq_id[2]), .Y (n_2));
  NAND4XL g1883__5122(.A (n_56), .B (n_96), .C (n_60), .D (n_59), .Y
       (irq_id[2]));
  NOR2XL g1884__8246(.A (n_61), .B (n_66), .Y (n_67));
  NAND2XL g1885__7098(.A (n_63), .B (n_65), .Y (n_66));
  NOR2XL g1886__6131(.A (n_30), .B (n_57), .Y (n_65));
  NAND2BX1 g1887__1881(.AN (n_59), .B (n_96), .Y (n_64));
  NOR4X1 g1888__5115(.A (n_22), .B (n_31), .C (n_49), .D (n_62), .Y
       (n_63));
  AOI221X1 g1889__7482(.A0 (n_40), .A1 (n_49), .B0 (n_13), .B1 (n_38),
       .C0 (n_42), .Y (n_60));
  OAI211X1 g1890__4733(.A0 (n_48), .A1 (n_6), .B0 (n_52), .C0 (n_45),
       .Y (n_62));
  NAND2XL g1891__6161(.A (n_44), .B (n_55), .Y (n_61));
  OAI211X1 g1892__9315(.A0 (n_48), .A1 (n_9), .B0 (n_6), .C0 (n_50), .Y
       (n_57));
  AOI221X1 g1893__9945(.A0 (n_40), .A1 (n_51), .B0 (n_13), .B1 (n_36),
       .C0 (n_43), .Y (n_59));
  AOI222XL g1895__2346(.A0 (n_13), .A1 (n_34), .B0 (n_5), .B1 (n_36),
       .C0 (n_46), .C1 (u4_priority_ptr[2]), .Y (n_56));
  AOI222XL g1896__1666(.A0 (n_47), .A1 (n_31), .B0 (n_40), .B1 (n_33),
       .C0 (n_29), .C1 (n_19), .Y (n_55));
  OAI21X1 g1897__7410(.A0 (n_8), .A1 (n_44), .B0 (n_39), .Y (n_54));
  AOI22X1 g1899__5477(.A0 (n_40), .A1 (n_35), .B0 (n_19), .B1 (n_24),
       .Y (n_52));
  INVX1 g1900(.A (n_50), .Y (n_51));
  CLKINVX1 g1901(.A (n_48), .Y (n_47));
  AOI21X1 g1902__2398(.A0 (n_19), .A1 (n_35), .B0 (n_24), .Y (n_50));
  AO21X1 g1903__5107(.A0 (n_19), .A1 (n_33), .B0 (n_29), .Y (n_49));
  NAND2XL g1904__6260(.A (n_19), .B (n_40), .Y (n_48));
  INVX1 g1905(.A (n_45), .Y (n_46));
  AO22XL g1906__4319(.A0 (n_5), .A1 (n_32), .B0 (u4_priority_ptr[2]),
       .B1 (n_30), .Y (n_43));
  OAI21X1 g1907__8428(.A0 (n_8), .A1 (n_14), .B0 (n_41), .Y (n_42));
  MXI2XL g1908__5526(.A (n_32), .B (n_30), .S0 (u4_priority_ptr[1]), .Y
       (n_45));
  MX2X1 g1909__6783(.A (n_37), .B (n_14), .S0 (u4_priority_ptr[1]), .Y
       (n_44));
  NAND2BX1 g1910__3680(.AN (n_37), .B (n_5), .Y (n_41));
  NAND2XL g1911__1617(.A (n_5), .B (n_38), .Y (n_39));
  AOI211X1 g1912__2802(.A0 (n_8), .A1 (u4_priority_ptr[0]), .B0 (n_5),
       .C0 (n_18), .Y (n_40));
  NAND2BX1 g1913__1705(.AN (n_24), .B (n_20), .Y (n_34));
  NAND2XL g1914__5122(.A (n_25), .B (n_21), .Y (n_38));
  NOR2BX1 g1915__8246(.AN (n_9), .B (n_22), .Y (n_37));
  NAND2XL g1916__7098(.A (n_28), .B (n_23), .Y (n_36));
  NAND2XL g1917__6131(.A (n_20), .B (n_23), .Y (n_35));
  NAND2BX1 g1919__1881(.AN (n_27), .B (n_21), .Y (n_33));
  OAI21X1 g1920__5115(.A0 (n_7), .A1 (n_9), .B0 (n_26), .Y (n_32));
  OAI21X1 g1921__7482(.A0 (u4_priority_ptr[0]), .A1 (n_9), .B0 (n_25),
       .Y (n_31));
  MXI2XL g1922__4733(.A (n_10), .B (n_14), .S0 (u4_priority_ptr[0]), .Y
       (n_30));
  OAI21X1 g1923__6161(.A0 (u4_priority_ptr[0]), .A1 (n_12), .B0 (n_15),
       .Y (n_29));
  NAND2XL g1925__9315(.A (u4_priority_ptr[0]), .B (n_17), .Y (n_28));
  NOR2XL g1926__9945(.A (n_7), .B (n_11), .Y (n_27));
  NAND2XL g1927__2883(.A (n_7), .B (n_16), .Y (n_26));
  NAND2XL g1928__2346(.A (u4_priority_ptr[0]), .B (n_16), .Y (n_25));
  NOR2XL g1929__1666(.A (u4_priority_ptr[0]), .B (n_15), .Y (n_24));
  NOR3X1 g1930__7410(.A (u4_priority_ptr[1]), .B (n_8), .C
       (u4_priority_ptr[0]), .Y (n_18));
  OR2X1 g1931__6417(.A (u4_priority_ptr[0]), .B (n_11), .Y (n_23));
  NOR2XL g1932__5477(.A (n_7), .B (n_10), .Y (n_22));
  NAND2XL g1933__2398(.A (n_7), .B (n_17), .Y (n_21));
  OR2X1 g1934__5107(.A (n_7), .B (n_12), .Y (n_20));
  MXI2XL g1935__6260(.A (u4_priority_ptr[0]), .B (n_7), .S0
       (u4_priority_ptr[1]), .Y (n_19));
  NOR2BX1 g1936__4319(.AN (irq[4]), .B (mask[4]), .Y (n_17));
  NOR2BX1 g1937__8428(.AN (irq[3]), .B (mask[3]), .Y (n_16));
  NAND2BX1 g1938__5526(.AN (mask[7]), .B (irq[7]), .Y (n_15));
  NAND2BX1 g1939__6783(.AN (mask[0]), .B (irq[0]), .Y (n_14));
  NOR2XL g1940__3680(.A (u4_priority_ptr[2]), .B (u4_priority_ptr[1]),
       .Y (n_13));
  NAND2BX1 g1941__1617(.AN (mask[6]), .B (irq[6]), .Y (n_12));
  NAND2BX1 g1942__2802(.AN (mask[5]), .B (irq[5]), .Y (n_11));
  NAND2BX1 g1943__1705(.AN (mask[1]), .B (irq[1]), .Y (n_10));
  NAND2BX1 g1944__5122(.AN (mask[2]), .B (irq[2]), .Y (n_9));
  CLKINVX1 g1946(.A (u4_priority_ptr[2]), .Y (n_8));
  CLKINVX1 g1948(.A (u4_priority_ptr[0]), .Y (n_7));
  AND2X1 g2__8246(.A (n_28), .B (n_26), .Y (n_6));
  NOR2BX1 g1949__7098(.AN (u4_priority_ptr[1]), .B
       (u4_priority_ptr[2]), .Y (n_5));
  SDFFRHQX1 \u4_priority_ptr_reg[1] (.RN (n_0), .CK (clk), .D
       (u4_priority_ptr[1]), .SI (n_3), .SE (cpu_ack), .Q
       (u4_priority_ptr[1]));
  SDFFRHQX1 \u4_priority_ptr_reg[2] (.RN (n_0), .CK (clk), .D
       (u4_priority_ptr[2]), .SI (n_4), .SE (cpu_ack), .Q
       (u4_priority_ptr[2]));
  SDFFRHQX1 \u4_priority_ptr_reg[0] (.RN (n_0), .CK (clk), .D
       (u4_priority_ptr[0]), .SI (n_1), .SE (cpu_ack), .Q
       (u4_priority_ptr[0]));
  OAI21X1 g1024__6131(.A0 (n_2), .A1 (n_72), .B0 (n_71), .Y (n_4));
  MXI2XL g1025__1881(.A (n_1), .B (irq_id[0]), .S0 (irq_id[1]), .Y
       (n_3));
  INVX1 g1027(.A (irq_id[0]), .Y (n_1));
  INVXL g1028(.A (reset), .Y (n_0));
  AOI221X1 g2(.A0 (n_13), .A1 (n_27), .B0 (n_47), .B1 (n_29), .C0
       (n_54), .Y (n_96));
endmodule

